apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:
        - name: postgres-storage # Defines a volume named postgres-storage that will be used to store PostgreSQL data.
          persistentVolumeClaim:
            claimName: postgres-pvc # This links the volume to the PersistentVolumeClaim defined in postgres-pvc.yml.
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password-secret # Refers to a Kubernetes Secret that contains the PostgreSQL password.
                  key: PGPASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage # Mounts the persistent volume claim to the container.
              mountPath: /var/lib/postgresql/data # This is the default directory where PostgreSQL stores its data.
              subPath: postgres-data # subPath allows you to specify a directory within the volume to mount, useful for organizing data.
      
