apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce # ReadWriteOnce - allows the volume to be mounted as read-write by a single node, ReadOnlyMany - allows multiple nodes to read the volume, ReadWriteMany - allows multiple nodes to read and write to the volume.
  resources:
    requests:
      storage: 2Gi # Requests 2Gi of storage for the PostgreSQL database.