name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        working-directory: react-frontend
      - run: docker build -t sanjoke/react-frontend -f Dockerfile.dev .
        working-directory: react-frontend
      - run: docker run -e CI=true sanjoke/react-frontend npm run test
        working-directory: react-frontend
